# Generated by Django 3.0.5 on 2020-08-26 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20200824_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_dislike',
            field=models.ManyToManyField(blank=True, related_name='user_comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='user_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
